---
name: Build
'on':
  push:
    branches:
      - "main"
  pull_request:

jobs:

  makepkg:
    name: makepkg
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - pkg: assetfinder
          - pkg: docker-prune
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Exit if pkg doesn't exist.
        run: if [[ ! $(git ls-remote "https://aur.archlinux.org/${{ matrix.pkg }}.git") ]]; then exit 1; fi

      - name: Download and Extract package.
        run: |
          curl -OL "https://aur.archlinux.org/cgit/aur.git/snapshot/${{ matrix.pkg }}.tar.gz"
          tar -xvzf "${{ matrix.pkg }}.tar.gz"

      - name: Pull devel image.
        run: docker pull quay.io/aminvakil/archlinux:devel

      - name: Run a container of devel image and mount package on it.
        run: |
          container_id=$(mktemp)
          docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v "${PWD}/${{ matrix.pkg }}":/pkg quay.io/aminvakil/archlinux:devel > "${container_id}"
          echo "container_id=$container_id" >> $GITHUB_ENV

      - name: Execute stuff before makepkg if there is any.
        run: |
          if [ -f "ci/${{ matrix.pkg }}/before_makepkg.sh" ]; then
              shellcheck "ci/${{ matrix.pkg }}/before_makepkg.sh"
              docker exec -i "$(cat ${container_id})" sh < "ci/${{ matrix.pkg }}/before_makepkg.sh"
          fi

      - name: Upgrade all packages.
        run: docker exec "$(cat ${container_id})" pacman -Syu --noconfirm

      - name: Change ownership of package folder
        run: "docker exec $(cat ${container_id}) chown -R devel: /pkg"

      - name: Makepkg!
        run: docker exec "$(cat ${container_id})" su devel sh -c "cd /pkg && makepkg -sri --check --noconfirm"

      - name: Execute stuff after makepkg if there is any.
        run: |
          if [ -f "ci/${{ matrix.pkg }}/after_makepkg.sh" ]; then
              shellcheck "ci/${{ matrix.pkg }}/after_makepkg.sh"
              docker exec -i "$(cat ${container_id})" sh < "ci/${{ matrix.pkg }}/after_makepkg.sh"
          fi

      - name: Prepare package for Pull Request.
        run: |
          sudo chown -R runner:docker .
          mkdir -p "pkgbuilds/${{ matrix.pkg }}"
          mv "${{ matrix.pkg }}/PKGBUILD" "pkgbuilds/${{ matrix.pkg }}/PKGBUILD"

      - name: Create Pull Request
        if: github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ matrix.pkg }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ matrix.pkg }}
          delete-branch: true
          title: ${{ matrix.pkg }}
          body: ${{ matrix.pkg }}
          draft: false
          add-paths: |
            "pkgbuilds/${{ matrix.pkg }}"
            "pkgbuilds/${{ matrix.pkg }}/PKGBUILD"

      - name: Stop and remove container forcefully.
        run: docker rm -f "$(cat ${container_id})"
